{
    "id": "CVE-2014-0472",
    "cisaKEV": false,
    "reported_exploited": false,
    "exploit_maturity": "poc",
    "counts": {
        "public_exploit_count": 1
    },
    "timeline": {
        "nvd_published": "2014-04-23"
    },
    "exploits": [
        {
            "url": "https://github.com/christasa/CVE-2014-0472",
            "name": "CVE-2014-0472 Django unexpected code execution using reverse()",
            "source": "github",
            "date_added": "2020-09-23",
            "exploit_maturity": "poc"
        }
    ]
}