{
    "id": "CVE-2022-22818",
    "cisaKEV": false,
    "reported_exploited": false,
    "exploit_maturity": "poc",
    "counts": {
        "public_exploit_count": 1
    },
    "timeline": {
        "nvd_published": "2022-02-03"
    },
    "exploits": [
        {
            "url": "https://github.com/Prikalel/django-xss-example",
            "name": "This repo reproduce xss attack on django 4.0.1 (see CVE-2022-22818)",
            "source": "github",
            "date_added": "2022-12-10",
            "exploit_maturity": "poc"
        }
    ]
}